name: Daily README Commit

on:
  schedule:
    # İstanbul UTC+3 -> 23:00 yerel = 20:00 UTC
    - cron: "0 20 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with PAT for pushing)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: pip install python-dateutil

      - name: Run updater (1–3 random commits)
        env:
          GH_EMAIL: ${{ secrets.GH_EMAIL }}
          GH_NAME: ${{ secrets.GH_NAME }}
        run: |
          git config user.email "$GH_EMAIL"
          git config user.name "$GH_NAME"
          python .github/scripts/update_readme_template.py
